export const modulesCibersecurity = (additionalDays) => [
    { moduleName: "Networking introduction", duration: 1 },
    { moduleName: "Network Conectivity", duration: 1 },
    { moduleName: "Network Architecture", duration: 1 },
    { moduleName: "Introduction to linux", duration: 1 },
    { moduleName: "Linux Administration", duration: 1 },
    { moduleName: "Kali Linux", duration: 1 },
    { moduleName: "Server administration", duration: 1 },
    { moduleName: "Server back up", duration: 1 },
    { moduleName: "Monitoring & optimization", duration: 1 },
    { moduleName: "Network Security", duration: 1 },
    { moduleName: "Protect your data and web", duration: 1 },
    { moduleName: "Incident Managment", duration: 1 },
    { moduleName: "Prevent/Detect Intruders", duration: 1 },
    { moduleName: "ACL, Firewall and Wifi", duration: 1 },
    { moduleName: "Cloud/Hosting Security", duration: 1 },
    { moduleName: "Pentesting Reconnaissance", duration: 2 },
    { moduleName: "Machine's Reconnaissance", duration: 1 },
    { moduleName: "Pentesting Exploitation", duration: 2 },
    { moduleName: "Report and Mitigate", duration: 1 },
    { moduleName: "Red Team for Web", duration: 2 },
    { moduleName: "Red Team for Machine", duration: 2 },
    { moduleName: "Blue Team on the Network", duration: 2 },
    { moduleName: "Blue Team on the Machine", duration: 2 },
    { moduleName: "SIEM", duration: 1 },
    { moduleName: "Data Loss Prevention", duration: 1 },
    { moduleName: "Digital Forensics", duration: 1 },
    { moduleName: "Final Project Start", duration: 1 },
    { moduleName: "ISO 27001", duration: 1 },
    { moduleName: "Cyberintelligence & OSINT", duration: 1 },
    { moduleName: "NIST", duration: 1 },
    { moduleName: "Spain's ENS", duration: 1 },
    { moduleName: "Final Project End", duration: 10 + additionalDays },
    { moduleName: "Last Day: Project Showroom", duration: 1 },
]; 