export const modulesDataScience = (additionalDays) => [
    { moduleName: "Prework Review", duration: 1 },
    { moduleName: "Pandas", duration: 1 },
    { moduleName: "Data Visualization", duration: 1 },
    { moduleName: "Intro to SQL", duration: 1 },
    { moduleName: "Web Scraping", duration: 1 },
    { moduleName: "API Requests", duration: 1 },
    { moduleName: "Calculus and L. Algebra", duration: 1 },
    { moduleName: "Probability", duration: 1 },
    { moduleName: "Descriptive Statistics", duration: 1 },
    { moduleName: "Hypothesis Testing", duration: 1 },
    { moduleName: "Algorithm Optimization", duration: 2 },
    { moduleName: "Exploratory Data Analysis", duration: 3 },
    { moduleName: "Your first ML Algorithm", duration: 2 },
    { moduleName: "Linear Regression", duration: 2 },
    { moduleName: "Random Forest Algo.", duration: 1 },
    { moduleName: "Boosting Algorithms", duration: 1 },
    { moduleName: "Naive Bayes Algorithm", duration: 1 },
    { moduleName: "K-nearest neighbors", duration: 1 },
    { moduleName: "Unsupervised learning", duration: 1 },
    { moduleName: "Time Series forecasting", duration: 2 },
    { moduleName: "Intro to Deep Learning", duration: 2 },
    { moduleName: "Deep Learning", duration: 2 },
    { moduleName: "Intro to NLP", duration: 2 },
    { moduleName: "Recommendation Systems", duration: 1 },
    { moduleName: "ML web app using Flask", duration: 1 },
    { moduleName: "ML webapp using Streamlit", duration: 1 },
    { moduleName: "Cloud Computing for ML", duration: 1 },
    { moduleName: "Final Project", duration: 11 + additionalDays },
    { moduleName: "Last Day: Project Showroom", duration: 1 }
]; 